"""Deterministic MA-crossover backtest workflow dispatcher (Patch 7)."""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any, Optional

from src.agent.backtest_intent import BacktestIntent, detect_backtest_intent
from src.agent.market_data_dispatcher import _sanitize

# auto-generated, Patch 7 — do NOT edit this template manually.
_MA_CROSSOVER_TEMPLATE = """\
# auto-generated, Patch 7 — MA crossover signal engine.
# Do NOT edit this file manually; it is overwritten on every backtest run.
from typing import Dict

import pandas as pd

FAST_WINDOW = {fast_window}
SLOW_WINDOW = {slow_window}


class SignalEngine:
    def generate(self, data_map: Dict[str, pd.DataFrame]) -> Dict[str, pd.Series]:
        signals = dict()
        for code, df in data_map.items():
            close = df["close"].astype(float)
            fast_ma = close.rolling(FAST_WINDOW, min_periods=1).mean()
            slow_ma = close.rolling(SLOW_WINDOW, min_periods=1).mean()
            signal = pd.Series(0.0, index=df.index)
            signal[fast_ma > slow_ma] = 1.0
            signals[code] = signal
        return signals
"""

_REQUIRED_METRIC_KEYS = ("sharpe", "max_drawdown", "total_return", "trade_count")


def _trace(trace: Any, event_type: str, **kwargs: Any) -> None:
    trace.write({"event": event_type, "type": event_type, **kwargs})


def _write_config(run_dir: Path, intent: BacktestIntent) -> None:
    safe_code = intent.symbol.replace("/", "-").upper()
    config = {
        "strategy_type": intent.strategy_type,
        "source": "ccxt",
        "engine": "daily",
        "interval": "1D",
        "codes": [safe_code],
        "symbol": intent.symbol,
        "fast_window": intent.fast_window,
        "slow_window": intent.slow_window,
        "start_date": intent.start_date,
        "end_date": intent.end_date,
        "initial_capital": intent.initial_capital,
    }
    (run_dir / "config.json").write_text(json.dumps(config, indent=2), encoding="utf-8")


def _write_signal_engine(run_dir: Path, intent: BacktestIntent) -> None:
    code_dir = run_dir / "code"
    code_dir.mkdir(parents=True, exist_ok=True)
    (code_dir / "signal_engine.py").write_text(
        _MA_CROSSOVER_TEMPLATE.format(
            fast_window=intent.fast_window,
            slow_window=intent.slow_window,
        ),
        encoding="utf-8",
    )


def _read_metrics(run_dir: Path) -> Optional[dict]:
    csv_path = run_dir / "artifacts" / "metrics.csv"
    if not csv_path.is_file():
        return None
    with csv_path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
    if not rows:
        return None
    return rows[0]


def _validate_metrics(metrics: dict) -> bool:
    for key in _REQUIRED_METRIC_KEYS:
        if key not in metrics:
            return False
        try:
            float(metrics[key])
        except (ValueError, TypeError):
            return False
    return True


def _format_result(intent: BacktestIntent, metrics: dict) -> str:
    sharpe = float(metrics.get("sharpe", 0))
    max_dd = float(metrics.get("max_drawdown", 0))
    total_ret = float(metrics.get("total_return", 0))
    trades = int(float(metrics.get("trade_count", 0)))
    lines = [
        f"Backtest: MA Crossover {intent.fast_window}/{intent.slow_window} on {intent.symbol}",
        f"Period: {intent.start_date} → {intent.end_date}  |  Capital: {intent.initial_capital:,.0f} USDT",
        "",
        f"  Sharpe ratio    : {sharpe:.4f}",
        f"  Max drawdown    : {max_dd:.2%}",
        f"  Total return    : {total_ret:.2%}",
        f"  Number of trades: {trades}",
    ]
    return "\n".join(lines)


class BacktestWorkflowDispatcher:
    ROUTED_BY = "backtest_workflow"

    def try_route(
        self,
        user_message: str,
        registry: Any,
        trace: Any,
        run_dir: str,
    ) -> Optional[dict]:
        intent = detect_backtest_intent(user_message)
        if intent is None:
            return None

        _trace(trace, "router", name=self.ROUTED_BY, intent={
            "symbol": intent.symbol,
            "fast_window": intent.fast_window,
            "slow_window": intent.slow_window,
            "start_date": intent.start_date,
            "end_date": intent.end_date,
            "initial_capital": intent.initial_capital,
        })

        real_run_dir = Path(run_dir)

        try:
            _write_config(real_run_dir, intent)
        except Exception as exc:
            return self._fail(_sanitize(str(exc)), "write_config_failed", trace)

        _trace(trace, "workflow_step", name="write_config", path_rel="config.json")

        try:
            _write_signal_engine(real_run_dir, intent)
        except Exception as exc:
            return self._fail(_sanitize(str(exc)), "write_signal_engine_failed", trace)

        _trace(trace, "workflow_step", name="write_signal_engine",
               path_rel="code/signal_engine.py")

        _trace(trace, "tool_call", name="backtest", args={"run_dir": run_dir})

        try:
            bt_result_raw = registry.execute("backtest", {"run_dir": run_dir})
        except Exception as exc:
            return self._fail(_sanitize(str(exc)), "backtest_tool_exception", trace)

        try:
            bt_result = (
                json.loads(bt_result_raw) if isinstance(bt_result_raw, str) else bt_result_raw
            )
        except (json.JSONDecodeError, TypeError):
            bt_result = {"status": "error", "error": "unparseable backtest result"}

        _trace(trace, "tool_result", name="backtest",
               status=bt_result.get("status", "unknown"))

        if bt_result.get("status") not in ("ok", "success"):
            return self._fail(
                _sanitize(bt_result.get("error", "backtest failed")),
                "backtest_failed",
                trace,
            )

        raw_metrics = _read_metrics(real_run_dir)
        if raw_metrics is None:
            return self._fail(
                "metrics.csv not found after backtest run", "metrics_missing", trace
            )

        if not _validate_metrics(raw_metrics):
            return self._fail(
                "metrics.csv missing required numeric fields", "metrics_invalid", trace
            )

        _trace(trace, "workflow_step", name="read_metrics",
               path_rel="artifacts/metrics.csv")

        content = _format_result(intent, raw_metrics)

        _trace(trace, "answer")
        _trace(trace, "end", status="success", iterations=0, routed_by=self.ROUTED_BY)

        return {
            "status": "success",
            "content": content,
            "iterations": 0,
            "routed_by": self.ROUTED_BY,
            "sharpe": float(raw_metrics["sharpe"]),
            "max_drawdown": float(raw_metrics["max_drawdown"]),
            "total_return": float(raw_metrics["total_return"]),
            "trade_count": int(float(raw_metrics["trade_count"])),
        }

    @staticmethod
    def _fail(reason: str, step: str, trace: Any) -> dict:
        _trace(trace, "end", status="failed", step=step, reason=reason)
        return {
            "status": "failed",
            "content": f"Backtest falhou: {reason}",
            "iterations": 0,
            "routed_by": BacktestWorkflowDispatcher.ROUTED_BY,
        }
